### ISSUE TITLE
Error while reading file from http://opendata.cern.ch/record/10

### ISSUE THREAD

**Issue by renato2099** [scikit-hep/root_pandas#86]
Hi there, I am trying to read a file from http://opendata.cern.ch/record/10 using root_pandas (master branch) with Python 2.7 and root with the following specs:
ROOT Version: 6.18/04
Built for linuxx8664gcc on Sep 11 2019, 15:38:23
From tags/v6-18-04@v6-18-04

However, I get the following error while reading a file. Any ideas/suggestions are much appreciated. Many thanks in advanced!
```python
from root_pandas import read_root
ifile = "/home/marenato/Downloads/physics_data/02186E3C-D277-E011-8A05-00215E21D516.root"
df = read_root(ifile, "Events")
```

```
TClass::Init:0: RuntimeWarning: no dictionary for class edm::TriggerResults is available
...
TClass::Init:0: RuntimeWarning: no dictionary for class DTSLRecSegment2D is available
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marenato/Documents/root_env/local/lib/python2.7/site-packages/root_pandas-0.7.0-py2.7.egg/root_pandas/readwrite.py", line 276, in read_root
    arr = root2array(paths, key, all_vars, selection=where, *args, **kwargs)
  File "/home/marenato/Documents/root_env/local/lib/python2.7/site-packages/root_numpy-4.8.0-py2.7-linux-x86_64.egg/root_numpy/_tree.py", line 241, in root2array
    warn_missing_tree)
  File "root_numpy/src/tree.pyx", line 629, in _librootnumpy.root2array_fromfile
  File "root_numpy/src/tree.pyx", line 402, in _librootnumpy.tree2array
TypeError: cannot convert leaf 'EventAuxiliary' of branch 'EventAuxiliary' with type 'edm::EventAuxiliary'
```

**Comment by chrisburr** [comment]
Do you know what information you want to get out of this file? At first glance it looks like it's deeply nested and filled with custom datatypes so it work work very well with the pandas model of working with data.

**Comment by renato2099** [comment]
hey @chrisburr  thanks for the reply!
I am working with the field "recoMuons_muons__RECO_".
I guess the error is because of the custom data type then, right?
Do you have any suggestions on how I could deal with these nested records and custom datatypes such that I can flatten them?

**Comment by chrisburr** [comment]
Personally I would use uproot and awkward array.

Unfortunately there is a bug which prevents this file from being read. I've opened and issue (https://github.com/scikit-hep/uproot/issues/448) and committed a very ugly hack which you can use to try it out for now (I expect it will be fixed properly very soon).

```bash
pip install --upgrade git+https://github.com/chrisburr/uproot.git@hack-around-coordinate-system
```

```python
import numpy as np
import uproot

f = uproot.open('root://eospublic.cern.ch//eos/opendata/cms/Run2010B/MuOnia/AOD/Apr21ReReco-v1/0000/02186E3C-D277-E011-8A05-00215E21D516.root')
tree = f['Events']
# Read all recoMuons_muons__RECO data for the first 1000 events
data = tree.arrays('recoMuons_muons__RECO.*', entrystop=1000, namedecode="utf-8")
```

I don't work with jagged data like this very often so please assume I'm doing things in stupid ways and read the uproot/awkward-array documentation for how to do it properly!

### Print out what columns we found (I'd suggest only loading what you need)

```python
print(*data.keys(), sep='\n')
```

```
recoMuons_muons__RECO.present
recoMuons_muons__RECO.obj
recoMuons_muons__RECO.obj.qx3_
recoMuons_muons__RECO.obj.pt_
recoMuons_muons__RECO.obj.eta_
recoMuons_muons__RECO.obj.phi_
recoMuons_muons__RECO.obj.mass_
recoMuons_muons__RECO.obj.vertex_.fCoordinates.fX
recoMuons_muons__RECO.obj.vertex_.fCoordinates.fY
recoMuons_muons__RECO.obj.vertex_.fCoordinates.fZ
recoMuons_muons__RECO.obj.pdgId_
recoMuons_muons__RECO.obj.status_
recoMuons_muons__RECO.obj.innerTrack_.product_.processIndex_
recoMuons_muons__RECO.obj.innerTrack_.product_.productIndex_
recoMuons_muons__RECO.obj.innerTrack_.index_
recoMuons_muons__RECO.obj.outerTrack_.product_.processIndex_
recoMuons_muons__RECO.obj.outerTrack_.product_.productIndex_
recoMuons_muons__RECO.obj.outerTrack_.index_
recoMuons_muons__RECO.obj.globalTrack_.product_.processIndex_
recoMuons_muons__RECO.obj.globalTrack_.product_.productIndex_
recoMuons_muons__RECO.obj.globalTrack_.index_
recoMuons_muons__RECO.obj.calEnergy_.tower
recoMuons_muons__RECO.obj.calEnergy_.towerS9
recoMuons_muons__RECO.obj.calEnergy_.em
recoMuons_muons__RECO.obj.calEnergy_.emS9
recoMuons_muons__RECO.obj.calEnergy_.emS25
recoMuons_muons__RECO.obj.calEnergy_.emMax
recoMuons_muons__RECO.obj.calEnergy_.had
recoMuons_muons__RECO.obj.calEnergy_.hadS9
recoMuons_muons__RECO.obj.calEnergy_.hadMax
recoMuons_muons__RECO.obj.calEnergy_.ho
recoMuons_muons__RECO.obj.calEnergy_.hoS9
recoMuons_muons__RECO.obj.calEnergy_.ecal_time
recoMuons_muons__RECO.obj.calEnergy_.ecal_timeError
recoMuons_muons__RECO.obj.calEnergy_.hcal_time
recoMuons_muons__RECO.obj.calEnergy_.hcal_timeError
recoMuons_muons__RECO.obj.calEnergy_.ecal_position.fCoordinates.fX
recoMuons_muons__RECO.obj.calEnergy_.ecal_position.fCoordinates.fY
recoMuons_muons__RECO.obj.calEnergy_.ecal_position.fCoordinates.fZ
recoMuons_muons__RECO.obj.calEnergy_.hcal_position.fCoordinates.fX
recoMuons_muons__RECO.obj.calEnergy_.hcal_position.fCoordinates.fY
recoMuons_muons__RECO.obj.calEnergy_.hcal_position.fCoordinates.fZ
recoMuons_muons__RECO.obj.calEnergy_.ecal_id.id_
recoMuons_muons__RECO.obj.calEnergy_.hcal_id.id_
recoMuons_muons__RECO.obj.combinedQuality_.updatedSta
recoMuons_muons__RECO.obj.combinedQuality_.trkKink
recoMuons_muons__RECO.obj.combinedQuality_.glbKink
recoMuons_muons__RECO.obj.combinedQuality_.trkRelChi2
recoMuons_muons__RECO.obj.combinedQuality_.staRelChi2
recoMuons_muons__RECO.obj.combinedQuality_.chi2LocalPosition
recoMuons_muons__RECO.obj.combinedQuality_.chi2LocalMomentum
recoMuons_muons__RECO.obj.combinedQuality_.localDistance
recoMuons_muons__RECO.obj.combinedQuality_.globalDeltaEtaPhi
recoMuons_muons__RECO.obj.combinedQuality_.tightMatch
recoMuons_muons__RECO.obj.combinedQuality_.glbTrackProbability
recoMuons_muons__RECO.obj.combinedQuality_.tkKink_position.fCoordinates.fX
recoMuons_muons__RECO.obj.combinedQuality_.tkKink_position.fCoordinates.fY
recoMuons_muons__RECO.obj.combinedQuality_.tkKink_position.fCoordinates.fZ
recoMuons_muons__RECO.obj.combinedQuality_.glbKink_position.fCoordinates.fX
recoMuons_muons__RECO.obj.combinedQuality_.glbKink_position.fCoordinates.fY
recoMuons_muons__RECO.obj.combinedQuality_.glbKink_position.fCoordinates.fZ
recoMuons_muons__RECO.obj.muMatches_
recoMuons_muons__RECO.obj.time_.nDof
recoMuons_muons__RECO.obj.time_.timeAtIpInOut
recoMuons_muons__RECO.obj.time_.timeAtIpInOutErr
recoMuons_muons__RECO.obj.time_.timeAtIpOutIn
recoMuons_muons__RECO.obj.time_.timeAtIpOutInErr
recoMuons_muons__RECO.obj.energyValid_
recoMuons_muons__RECO.obj.matchesValid_
recoMuons_muons__RECO.obj.isolationValid_
recoMuons_muons__RECO.obj.qualityValid_
recoMuons_muons__RECO.obj.caloCompatibility_
recoMuons_muons__RECO.obj.isolationR03_.sumPt
recoMuons_muons__RECO.obj.isolationR03_.emEt
recoMuons_muons__RECO.obj.isolationR03_.hadEt
recoMuons_muons__RECO.obj.isolationR03_.hoEt
recoMuons_muons__RECO.obj.isolationR03_.nTracks
recoMuons_muons__RECO.obj.isolationR03_.nJets
recoMuons_muons__RECO.obj.isolationR03_.trackerVetoPt
recoMuons_muons__RECO.obj.isolationR03_.emVetoEt
recoMuons_muons__RECO.obj.isolationR03_.hadVetoEt
recoMuons_muons__RECO.obj.isolationR03_.hoVetoEt
recoMuons_muons__RECO.obj.isolationR05_.sumPt
recoMuons_muons__RECO.obj.isolationR05_.emEt
recoMuons_muons__RECO.obj.isolationR05_.hadEt
recoMuons_muons__RECO.obj.isolationR05_.hoEt
recoMuons_muons__RECO.obj.isolationR05_.nTracks
recoMuons_muons__RECO.obj.isolationR05_.nJets
recoMuons_muons__RECO.obj.isolationR05_.trackerVetoPt
recoMuons_muons__RECO.obj.isolationR05_.emVetoEt
recoMuons_muons__RECO.obj.isolationR05_.hadVetoEt
recoMuons_muons__RECO.obj.isolationR05_.hoVetoEt
recoMuons_muons__RECO.obj.type_
```

### Play around with vertices

```python
vtx_x = data['recoMuons_muons__RECO.obj.vertex_.fCoordinates.fX']
vtx_y = data['recoMuons_muons__RECO.obj.vertex_.fCoordinates.fY']
vtx_z = data['recoMuons_muons__RECO.obj.vertex_.fCoordinates.fZ']
print('We have', np.count_nonzero(vtx_x.counts > 3), 'out of', len(vtx_x), 'events with more than 3 vertices')
```
```
We have 94 out of 1000 events with more than 3 vertices
```
```python
print('In the 5th event we have the following vertex positions:')
for x, y, z in zip(vtx_x[5], vtx_y[5], vtx_z[5]):
    print(f'    ({x:.4f}, {y:.4f}, {z:.4f})')
```
```
In the 5th event we have the following vertex positions:
    (0.0950, 0.0266, -1.9886)
    (0.0886, 0.0193, -2.0257)
```

**Comment by chrisburr** [comment]
The latest release of uproot can now read your file without my hack so I'll close this now. If you have an problems, feel free to open questions on stackoverflow as explained [in `uproot's` readme](https://github.com/scikit-hep/uproot#questions) (or as GitHub issues if it really looks like a bug).

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, would this be the moment to try and either close issues and PRs or else deal with as much as possible for a final release? It seems also that we should add a deprecation warning in the README.

**Comment by renato2099** [comment]
Thanks a lot for the pointer @chrisburr !
I will use the latest release of uproot then!
